import { DifficultyLevel, OperationType, Problem } from './types'
import {
  generateProblem,
  withUnknownPosition,
  getExpectedAnswer,
  UnknownPosition,
} from './mathUtils'
import i18n from './i18n'

// Phase 6 (plan §8.1): parameterized word-problem templates with theme/noun
// substitution. Numbers reuse the existing difficulty ranges via generateProblem.
// Story stems and theme nouns are translated via i18next so word problems
// follow the learner's language (issue #64).

type Theme = 'apples' | 'stickers' | 'marbles' | 'books' | 'balloons'

const THEME_KEYS: Record<Theme, string> = {
  apples: 'wordProblems.nouns.apples',
  stickers: 'wordProblems.nouns.stickers',
  marbles: 'wordProblems.nouns.marbles',
  books: 'wordProblems.nouns.books',
  balloons: 'wordProblems.nouns.balloons',
}

const THEMES: Theme[] = ['apples', 'stickers', 'marbles', 'books', 'balloons']

function nounFor(count: number, theme: Theme): string {
  // i18next count-based plural suffixes (_one/_other) pick the right
  // noun form for languages that inflect after numbers.
  return i18n.t(THEME_KEYS[theme], { count })
}

function randomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

/**
 * Build a word problem for the given difficulty + operation. The underlying
 * arithmetic problem is generated by the existing generateProblem so number
 * ranges stay consistent. The story stem replaces the bare equation in
 * ProblemCard; the answer to check is driven by getExpectedAnswer so the
 * word problem can also use a missing-operand unknown position.
 */
export function generateWordProblem(
  difficulty: DifficultyLevel,
  operation: Exclude<OperationType, 'mixed'>,
  options: { unknownPosition?: UnknownPosition } = {}
): Problem {
  const base = generateProblem(difficulty, operation)
  const theme = randomElement(THEMES)
  const noun = nounFor(Math.max(base.operand1, base.operand2), theme)

  const stem = i18n.t(`wordProblems.${operation}`, {
    n1: base.operand1,
    n2: base.operand2,
    noun,
  })

  let problem: Problem = { ...base, wordProblem: stem }
  if (options.unknownPosition) {
    problem = { ...problem, unknownPosition: options.unknownPosition }
  } else {
    problem = withUnknownPosition(problem, difficulty)
  }

  // For missing-operand word problems, rewrite the stem so the question asks
  // for the missing quantity instead of the result.
  if (problem.unknownPosition && problem.unknownPosition !== 'result') {
    problem.wordProblem = rewriteMissingOperand(problem, noun)
  }

  return problem
}

function rewriteMissingOperand(problem: Problem, noun: string): string {
  const { operand1, operand2, operation, correctAnswer, unknownPosition } = problem
  if (unknownPosition === 'operand1') {
    return i18n.t(`wordProblems.missingOperand1.${operation}`, {
      n2: operand2,
      total: correctAnswer,
      noun,
    })
  }
  if (unknownPosition === 'operand2') {
    return i18n.t(`wordProblems.missingOperand2.${operation}`, {
      n1: operand1,
      total: correctAnswer,
      noun,
    })
  }
  return problem.wordProblem ?? ''
}

/**
 * The plain-text sentence spoken by TTS (placeholders already resolved).
 */
export function getWordProblemSpeech(problem: Problem): string {
  return problem.wordProblem ?? ''
}

/**
 * Convenience: does this problem render as a word problem?
 */
export function isWordProblem(problem: Problem): boolean {
  return typeof problem.wordProblem === 'string' && problem.wordProblem.length > 0
}

/**
 * The numeric value the learner must enter, accounting for the unknown slot.
 */
export function wordProblemExpectedAnswer(problem: Problem): number {
  return getExpectedAnswer(problem)
}
