import { DifficultyLevel, OperationType, Problem } from './types'
import {
  generateProblem,
  withUnknownPosition,
  getExpectedAnswer,
  UnknownPosition,
} from './mathUtils'

// Phase 6 (plan §8.1): parameterized word-problem templates with theme/noun
// substitution. Numbers reuse the existing difficulty ranges via generateProblem.

type Theme = 'apples' | 'stickers' | 'marbles' | 'books' | 'balloons'

interface Template {
  operation: Exclude<OperationType, 'mixed'>
  // Templates use {n1}, {n2}, {noun}, {total} placeholders. The story is
  // written so the result is the natural unknown unless overridden.
  build: (n1: number, n2: number, noun: string, total: number) => string
}

const TEMPLATES: Template[] = [
  {
    operation: 'addition',
    build: (n1, n2, noun) =>
      `Mia has ${n1} ${noun}. She gets ${n2} more. How many ${noun} does Mia have now?`,
  },
  {
    operation: 'subtraction',
    build: (n1, n2, noun) =>
      `Liam has ${n1} ${noun}. He gives away ${n2}. How many ${noun} are left?`,
  },
  {
    operation: 'multiplication',
    build: (n1, n2, noun) =>
      `There are ${n1} boxes with ${n2} ${noun} in each box. How many ${noun} are there in total?`,
  },
  {
    operation: 'division',
    build: (n1, n2, noun) =>
      `${n1} ${noun} are shared equally among ${n2} friends. How many ${noun} does each friend get?`,
  },
]

const THEME_NOUNS: Record<Theme, { singular: string; plural: string }> = {
  apples: { singular: 'apple', plural: 'apples' },
  stickers: { singular: 'sticker', plural: 'stickers' },
  marbles: { singular: 'marble', plural: 'marbles' },
  books: { singular: 'book', plural: 'books' },
  balloons: { singular: 'balloon', plural: 'balloons' },
}

const THEMES: Theme[] = ['apples', 'stickers', 'marbles', 'books', 'balloons']

function pluralize(count: number, theme: Theme): string {
  const { singular, plural } = THEME_NOUNS[theme]
  return count === 1 ? singular : plural
}

function randomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

/**
 * Build a word problem for the given difficulty + operation. The underlying
 * arithmetic problem is generated by the existing generateProblem so number
 * ranges stay consistent. The story stem replaces the bare equation in
 * ProblemCard; the answer to check is driven by getExpectedAnswer so the
 * word problem can also use a missing-operand unknown position.
 */
export function generateWordProblem(
  difficulty: DifficultyLevel,
  operation: Exclude<OperationType, 'mixed'>,
  options: { unknownPosition?: UnknownPosition } = {}
): Problem {
  const base = generateProblem(difficulty, operation)
  const template = TEMPLATES.find((t) => t.operation === operation) ?? TEMPLATES[0]
  const theme = randomElement(THEMES)
  const noun = pluralize(Math.max(base.operand1, base.operand2), theme)

  const stem = template.build(base.operand1, base.operand2, noun, base.correctAnswer)

  let problem: Problem = { ...base, wordProblem: stem }
  if (options.unknownPosition) {
    problem = { ...problem, unknownPosition: options.unknownPosition }
  } else {
    problem = withUnknownPosition(problem, difficulty)
  }

  // For missing-operand word problems, rewrite the stem so the question asks
  // for the missing quantity instead of the result.
  if (problem.unknownPosition && problem.unknownPosition !== 'result') {
    problem.wordProblem = rewriteMissingOperand(problem, noun)
  }

  return problem
}

function rewriteMissingOperand(problem: Problem, noun: string): string {
  const { operand1, operand2, operation, correctAnswer, unknownPosition } = problem
  if (unknownPosition === 'operand1') {
    switch (operation) {
      case 'addition':
        return `Mia has some ${noun}. She gets ${operand2} more and now has ${correctAnswer}. How many ${noun} did Mia start with?`
      case 'subtraction':
        return `Liam had some ${noun}. He gave away ${operand2} and has ${correctAnswer} left. How many ${noun} did Liam start with?`
      case 'multiplication':
        return `Boxes of ${operand2} ${noun} each total ${correctAnswer}. How many boxes are there?`
      case 'division':
        return `${correctAnswer} ${noun} per friend, shared among ${operand2} friends. How many ${noun} were there in total?`
    }
  }
  if (unknownPosition === 'operand2') {
    switch (operation) {
      case 'addition':
        return `Mia has ${operand1} ${noun}. She gets some more and now has ${correctAnswer}. How many ${noun} did she get?`
      case 'subtraction':
        return `Liam has ${operand1} ${noun}. He gives some away and has ${correctAnswer} left. How many ${noun} did he give away?`
      case 'multiplication':
        return `There are ${operand1} boxes. Each box has the same number of ${noun}, for a total of ${correctAnswer}. How many ${noun} are in each box?`
      case 'division':
        return `${operand1} ${noun} are shared equally so each friend gets ${correctAnswer}. How many friends are sharing?`
    }
  }
  return problem.wordProblem ?? ''
}

/**
 * The plain-text sentence spoken by TTS (placeholders already resolved).
 */
export function getWordProblemSpeech(problem: Problem): string {
  return problem.wordProblem ?? ''
}

/**
 * Convenience: does this problem render as a word problem?
 */
export function isWordProblem(problem: Problem): boolean {
  return typeof problem.wordProblem === 'string' && problem.wordProblem.length > 0
}

/**
 * The numeric value the learner must enter, accounting for the unknown slot.
 */
export function wordProblemExpectedAnswer(problem: Problem): number {
  return getExpectedAnswer(problem)
}
